apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dRa8y0q0f3U4oiK3+nishIRlLzoyAbxd0g==,iv:M+K09D3j7ivU8RCUEeHOa9GP2a5+XkLYxzwhKs4AknI=,tag:Ab+LBiOPBgc+fveXQYJmNw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:8PFDPSVbhhu32efdGOYNRc2tU8xKV82j5rFOzZs0nchIdnj49A==,iv:6vHhlQlDcriyP0XOsDyuai7u+QAtdSXfKLjwfqYfZ1A=,tag:gRWii50z3RAxSfp19cwbrQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+AiUeyLjxCDfGeSkwOb1H0vmZjQ=,iv:ZGh/bKP7eRI5PAVlbGBGXsygPKqlhuwRGj1fr4w0i+U=,tag:Qs8FPdv4/sMwlhXV0wEPwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QXlNQ1E1ZHBkN1hQSktX
            OGtsTkQ0WThUVEUrU3I2WEtoVEljT0R4MUJFCnVyYWlwVDc5SkVjck9BemQxZ040
            UjU4Q1lneW1BdlZaREEzUHgzbDdaMlkKLS0tIHh0bXhlbFh5bjZiWmJ5YWFGQ1Fn
            ZXJ3bENDWTNxV012NGRibUtYcm5WTlEK6szqOOY7XCuYE8F2SB19l2SResfyhQNv
            UTTVz3Pc7kRlI0wTuyclhV/UxiUY26jWFqQSAn0+v7QOObMls/3kHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T09:11:44Z"
    mac: ENC[AES256_GCM,data:38NhUUepFUR+azk50lILml5Crz+JLkFZyftrEildraOOfI4wgv9zU7fyPQTtXX8Pg9dBa6lxZ5uTmKMzRu9UTJofRYj932wkGkQKofLCLPJksJapOzWNKc6ikbQRO50q5ardX0r96A2TdExlsmmd+IiEEq2BijaOElab9fVFdtg=,iv:jmCmOnk8hb960MscJComa7p+8W5cSKXMukvDj6DzcAg=,tag:tPDFgxxbT1DPUO5XFJrPhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
