---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sabnzbd/ks.yaml
