kind: ENC[AES256_GCM,data:ZasT8wyd,iv:9eg3JVTp8IUlV17xJmYKhnKZzxb/2ehAI1RqDbItgmE=,tag:yCSS9P7Vp+Bl3ehJ6MfWRQ==,type:str]
ansible_user: ENC[AES256_GCM,data:djge7g==,iv:L/p4BIeQ4Z+R+a68nkqxKvLptAu3blNUwBSmTiYb8Dc=,tag:dAjN9ZzO/4mWKhComd/jsw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zjLUAx0g,iv:9rqjBT6vq1VTi5+vzXj6tGXT+gt5FKFdVhTJjeQJZZg=,tag:02vzy4KeIkXUcXkrmRHhow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL2NmRGdkdDFJTEF1SEI3
            dkZHNXQ1YlBQYTU0b2xsWWxwdmF5UFlLYWxRCitHMVZZays3YURUOWdwZmhHb2N1
            YXpNZUc0MFJIRUNhR1JCODZCdzNqUWcKLS0tIGpIazNvMkNqWUtSdGdsZ3h4bGdI
            WkxZU2RtZU5DTTVzUzhCbXU1VWdPZ1EKao3n+h7y82w0vMS9ykE002/gHto37/6b
            1LO8gW96TUYe075zyhUtJBUiOrhBDvljT1a3u9Kpi+S2BBlB4pR/5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T10:33:39Z"
    mac: ENC[AES256_GCM,data:EeXscoSQVhu11sp004ZoxKYpY9t+qTqq/CDQRSTdZ1K8Sltr7acD0gKHiasLQNXWxJ5AKS6UQMJQ+izy3peY6z0eu2a6HH6s/NdWp6tTjeWLpVhUrXTGFdp4GCBR+WZ3XrZesK5/clnZg4eU6YkdrQexQVKyrfxmnnEmCaTUFhE=,iv:DT6GkkUIPEN9WGwzHCd7QkCYbyOxaRHLoBTC9qMlZwk=,tag:A61WVvsfKWCUH68rSKtlhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
