kind: ENC[AES256_GCM,data:WGg1psnQ,iv:zFb1lIedcq846UZ6IdyMh8ikUuMbVvlF9GSPfa6RCsQ=,tag:rKNu3MKLkDpFDJYqvc6zWQ==,type:str]
ansible_user: ENC[AES256_GCM,data:G0377g==,iv:UVOTx+EEokDsO4X7wVUiwpEF+LGlMfG1F/w4+K5Z6f4=,tag:WtTB59g1vGSN9KiwhsdguA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:J+Dy9njlBiG6,iv:qevR7nogK1jymY8NoYQ/3Sh5VJeiDX1Ratdp0rqTYRk=,tag:TiJWvdMgQKSaX/HFwXRgeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOW9KNFd6blY2YmNtU2xy
            OHBHNTREVjIwTkV3a3lOV0c4MjhTSlBsaVVrCnY4WGNQTkxmbmlzcnJtcmM4Si9H
            U0NNb01aZWZLMnlDbGlLRCtDc0dudTAKLS0tIDNjUzdnQUsvSVc4MUtmWG8xUncr
            Ymdid2xEeUFuNTg4UitCb25UVEhGcGsKW4wjXXPG/XcwAOf/VbwZA54QTmYe797p
            7Fqope/bdcJYYCTjV9hCYNYRoF3piqJuAKtPl8twldJH1SExQAEOkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T13:02:56Z"
    mac: ENC[AES256_GCM,data:mr3g4wB7K4E4jDYjiUtLn51zPSXCRiYn4bsmtlDkYbM4+YbVnaFjRA7rAs/fE1vJxVYdYaoPygdOgTeK9lvqVCQ8cbcqkYYRHFI/MZu0PJwZ3jn1SJ1jCIRqSYwNbuPmR4nTrhf7GEqexs/5SDVU3fJUQUf3+eSIA7UUnNj9lXk=,iv:aWMscifNu4i5ZPWlROLXErpd3vQIOPjPEnXmzLcbFlk=,tag:eHqMZuyL30u5tPmIK+QNYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
