kind: ENC[AES256_GCM,data:if0I7VZV,iv:D8vDGnNYnmRAe3NDn6gkBbOmsQH/7BRYCCcdYZwdR/s=,tag:IESt6KikcKk806eHRkt59A==,type:str]
ansible_user: ENC[AES256_GCM,data:H/3WYg==,iv:B0e92FQ3CltBxfKHjKyjCl5TX4bKQOMibJBbPqf57sY=,tag:SXaz7V3zRuy25hcgh6bMyQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Ch8BO/BM,iv:bnrKeJfXjKy8em5T0+Dd0oECNxpvHMPBZ+dSrgVj45A=,tag:TbLlt+jWGuSAmJYScKV9hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOalZoaitBbEVodzk0QkFt
            K25lcTR4U1d3T285RitxaG92aU9TbE5qVzNjCldMWWpZVWJ2Zk1Eejl2cndqUlc1
            T0l3cW5UN3pFVjZ4QWQxNVlwb3AzRUEKLS0tIDRwMmtHZWRTOVRUMks1ejRyNFZj
            Yi8wdDRlano5UW1JNlJwc0hzejg2NUUKm7qom+QqsMTNh1REQwuP6sb4QzW/iaHd
            8svfQsgBGO/NPjNxtcuYv6m16XWO/M+rqTjPzcNpH/PcaJWQjnML5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T10:33:39Z"
    mac: ENC[AES256_GCM,data:9ArsfR2bV3/4L4u/bpJbY7O+hgKjw7P2rWq30VRE3Cvdh2LslemRRQ/WUt686OSaC9dELRsb7OXd6o2eTt5kRJX22QrZcJOsHT+7K1CyL03ICNYNzlgWg5OnnxXoQ/L1qwEEWDTeT6Ijx4i0ZDDMx9myARtcCtKv53lRdY7mM3I=,iv:ZgYdN9pHuK9QVaYw94dtJoCZtKNbilqKmnoGVagTe4g=,tag:qTQUOdcD+QNBJOyfIwYgQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
