kind: ENC[AES256_GCM,data:nquXuj80,iv:u8z5s5xXXe01qM70cZ981ktQcFKQJnCiTegmJUW0cDk=,tag:JgVjL1PRCEYsx4EWWX7GVw==,type:str]
ansible_user: ENC[AES256_GCM,data:En/Udg==,iv:/QSRV0dDwDiEfGhM+U9ZY91ojGN9CcDsMu4pgc/hsoI=,tag:bK6cRQeANw07N9kyOt3AJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U8RJ7NSUH7Qf,iv:2srTfRWvfRiCM+kozN+R/Za4/5Hv8rcGz4h29Ehz01c=,tag:elf2/NH2R5thfHGpBHqWEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbG43RnNneXMyUnVJbFh3
            dzNicEljY1BRYkVUMGo2UE8yYWhpOFUyNERjClNRV2lnSjJkSml6R2VOd3ZvTWxT
            VjhFWGduWlpQWmlzbnJBNXJiREdTZmMKLS0tIHczM0hEc0xucmswd3VEcjJZZEN1
            YWEwN3IvR3p2SGhUdmN2d2JabDlERTQKTpNOrFtDAjFeyGDJzs828Y4gXRzP0nx6
            5R+3jGevyNyYQz5PAcjick1pw6Dzts1K7owJr8Is+xm+wRzCjaVkGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T10:33:39Z"
    mac: ENC[AES256_GCM,data:vRjEKEBzQsflt6ZGveI7eyllwda6ABcuiS+vkOJKzBXPoOnmPgmGFe9d5cycS0VCsKhVF2MPS6g5iarLa/1G4+R10W1tTO7o4SPKR7mSV375FnDVR8ybXtComgDmCEtc8Nth24lrBqkou1usZ1D0dX1rV+3MGWbYEnOoN64sRuk=,iv:Fvl+njaF3YGzva5BwFF/hRt+J1ybK24nMpZWoTTqds8=,tag:gFV2AudJXV75YU8PchVEXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
