kind: ENC[AES256_GCM,data:pZmN4mOc,iv:Zw1KDHv1B64zVugA/Y4aGSFGIo6HQb+mIjhpg/vI7nM=,tag:pDoqweYqu6p/EmHLgorP8w==,type:str]
ansible_user: ENC[AES256_GCM,data:2lkiBA==,iv:d7Mzuh+Ey6qO1qEqs/YybN/7dnQsx1snfgcmJWKmG6I=,tag:Mct3w5xg+AXEBjKDxe0tsA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Ujk/GQW2,iv:N4Zv1r/kcqxR32vv1cZMV9PeaKgGfm2FlzUrokYATpw=,tag:hriszh/c6rfDGojLemdV1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2UvbHliT3R6ZUd4elYy
            MWtldTJML1hTWjRDU0dxRXphOW4wdWRQemw4Ck9vN1ZsN3duT2dBZm9WSlZFT09M
            THhpSklRcUpKeXl5aXBnM2xoR2YrdEkKLS0tIFArS1pOREhubDFJelBINWxtanlk
            VTBmdjJjOEQ0SEJrMDE1OUFkMkd4VzgKGSdHIts34T0XBBfJx3U8kPwJWK7Sc8l+
            GUcD6/gQkUED75ogSI3U61VxRVJK+ksLxXQG+Cx5BbXGAFvrw9HYTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T10:33:39Z"
    mac: ENC[AES256_GCM,data:YHG1+1vJjEe2O6Ps7T8vLoJZrtZ5xAuEfwQwfPFqz6JpEHrrAGrDdiZXxgpk+GnPWUJfGT4gJsFNZAAxpviatZN3NMMWMZbrEDSQ0kpkgkNi1jr+eJDC41IYrJvYQlVMSmGNZ2YvSNAZjMqDSIaCDDBwSWsf1lXRxxnk5790/5U=,iv:NM1ZYdfDTgUMpMng7njNhAU/zWgj0QAZ5lnlg649aLA=,tag:hI6aiw33GW2/HKjt9nU/kw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
