---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # controller:
    #   type: statefulset
    #   annotations:
    #     reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 3.7.2@sha256:666a2affaaef70fa6b15c3b833db984c419a9cf8c3d994ad55d19e45ec9e3ad4
    env:
      TZ: Australia/Sydney
      SABNZBD__PORT: &port 80
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.default,
        sabnzbd.default.svc,
        sabnzbd.default.svc.cluster,
        sabnzbd.default.svc.cluster.local,
        sab.${SECRET_DOMAIN}
    # envFrom:x`x`
    #   - secretRef:
    #       name: sabnzbd-secret
    service:
      main:
        ports:
          http:
            port: *port
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api?mode=version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    # podAnnotations:
    #   setGateway: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "sab.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /config
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #     storageClass: ceph-block
    # Note: If downloading very large nzbs it might be worth using NFS for your download directory.
    # persistence:
    #   media:
    #     enabled: true
    #     type: nfs
    #     server: expanse.turbo.ac
    #     path: /eros/Media
    #     mountPath: /media
    #   incomplete:
    #     enabled: true
    #     type: emptyDir
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      media:
        enabled: true
        type: nfs
        server: 10.0.0.165
        path: /volume1/Main/data/usenet
        mountPath: /usenet
      # incomplete:
      #   enabled: true
      #   type: nfs
      #   server: 10.0.0.165
      #   path: /volume1/Main/data/usenet/incomplete
      #   mountPath: /Main
    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 3000Mi
