apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fLzftjAN4/Ul/yVeCXAF6H3KstCH0ZID7QViAdqCLJP5If4VpbYiww==,iv:/6Gsg7QoOKjOFfYd8AZsbdNXpNUBHly3Vq8Fz/ZCFZQ=,tag:hG44ryVye9pn1dGIT5gXsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVWJNOGpuT2FWbVJkNzNa
            VStRaUQ5VnNqdEhqTk9IU0d5Y1VBeEN2UDBzCllwbEZyUEVGTUdNTmgzYUFhYUtS
            NTRObDJ0c29MWHpWdUpVTHU3U0ZMcTgKLS0tIHlDRkdDNDd6WGRibFRZZnFpRzFK
            SUFGalYwNFBEMUdHMWlLMlMwYmI1WUkKjdl4fGWVex+4uBOMsFq1xDfb2WtL13tw
            Czk+ZyEUtIn5Vi73qU2DLhdX8IOpJ9tdO/i0XTLYGmNNAAvMBb8yDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T09:11:44Z"
    mac: ENC[AES256_GCM,data:omzqV0SILcrHjN0dSKet9QsjCUwHLV/J7be1giKs52KTAyMjHXaIKff0zM8JFuvCZCqJboLCmbUJIZQ5lj3mg2qVf/EUpBaY2qimTiCoHb/y7ONnRboK8iZ0kmtrnXRD1iFN/0O9puOpR2OxFhfffTyRR/PtXJD9kb9RcFfCZ78=,iv:cJH6ec2orGW8HbFRvIj1wTS00r9ZyxB9TRp80C+xdfU=,tag:FK5JoBY9VAI0a8RqEUWnOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
