apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bXYIfPAUDUpDKOQlIn0be4+BFlvhBT471N4Nsr4WgWd99ht1fHnDcA==,iv:/srx+M/iYYRQYPXv08vAOqnAaqce3Q6UHcIxH5b/9rk=,tag:fqCTjgHv+Jr9QfIRqMvrXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNUIrN1gzVm82dnVGaDN5
            SXU1OGVKaDBQOVVDOFloNEdZZTlMakRZeTBRCm5mR2xUV2k3b0lhUVdiMlpxMjlj
            NnJPQ3NMYVpFS25XL2x1RkxwZ1NROFUKLS0tIEJ4TDhMUDZySlhKdDJmSG5lMnJv
            YVFPa09LUURLRlU1RExDTFJTTkVpazgK94EwL+5GnoPa8kkwkSJVP1EBUvwHSd9j
            AwXUbJWylm8H2B6yaRCRNQdjXiiRWdhmIC0pxUkJpOqgIqJUUVyxaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T10:33:39Z"
    mac: ENC[AES256_GCM,data:pgpF+7ETgnBWfQb3IBTLK5tBan1ouew8sE2unZNAnDT3LpePSDv0YCQNZSBcXIJb8r2whPZwEI6OZLJhIOyzoM4PeFFGeZ5bqi9XY3KilQdpuNiJs7nZHl7SttMIVLaNYyRd8VTmClTMcnc6NKVlanBCueSI04QahpTsJc36k0o=,iv:8hsdXn5ytWaTOXNPWOEKjiqXD/tGIlmc8Azsj2sZiGs=,tag:HxtT9CENczPcl+5qRc9vQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
