apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:R1AS7YY5f//ZRAkyrLcCIGeCabePouvwyVlaM44rcUMEI0/A8G9oPw==,iv:wdkdbKwG+WPLCGb8V0su00Z11br4pjuPYCbNlw5/cMY=,tag:AywG7MQ9DBMrq9cJIHsq5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZGhoaWZ4K2w3T0FGQ0M2
            TzlubFZDb2JMQmZ5ZU9ocTh5NVo4Wkh3SVZNCmtrbVhsNzVVaDJadDY4VkRVMVBO
            N094WGdWV3o4aysxbHNMdW9EbzV6VkkKLS0tIHpmeHRzR3VuV1Fsd2FoKzdlcElx
            Y1RGRlVvazk0Qk9WaVNENXRWemV2bU0KEeej4Mw/Rk8e+TQkIsQLZm0LIo0oVZKt
            v/o3pzqWEO3V3gR+1pBChjFrj7ejLsRnJlL9Ub0ece0Rl+i6NhI2aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T13:02:56Z"
    mac: ENC[AES256_GCM,data:VN8Z1pGU1xyWMpfP8sOa03oQW+NcT/nC1zzvD7WRRbE+RKaPlIcqgytW5pcV+nly3i9iMlc+FMeCIp7FtsxKCXgX+5fjQnWInW5MuVtndARoOelvAdybbi8ufcr6Z9PPPaaX42bUUBclSoLVGYF22k0r0kgK1baxawIV4P+YtyU=,iv:qzSTn+povHnR7Ix1RRRTmVzDhifnU9K1MahkEzJLaOo=,tag:FwzE57UMpvsHDb3OFsYTtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
