---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.9@sha256:ed845a77d7923e8bbfdb8a4eef125d41b6e5e3b2799668369464fe58ca980fd0

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]

    env:
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
      JELLYFIN_CACHE_DIR: "/media/cache"

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        #loadBalancerIP: "${SVC_JELLYFIN_ADDR}"
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      media:
        enabled: true
        type: nfs
        server: 10.0.0.165
        path: /volume1/Main/data/media
        mountPath: /media
      # transcode:
      #   enabled: true
      #   type: emptyDir

    # nodeSelector:
    #   intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 100m
        # gpu.intel.com/i915: 1
        memory: 500m
      limits:
        # gpu.intel.com/i915: 1
        memory: 2G
