apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:m4HM7g==,iv:wJYrmrNvJZgYmoHx0SeufA8A/Z/iW8DnuR5LjzaTZeQ=,tag:kuYUSAcO4/W5lqh43Io49g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:WpQfKGdtp6lsy+dZLjuYcSA1HvIXGwPmUKyRTM2xl6voECJUi6IxZkwFhaQ=,iv:6k65/HUVRvfWU0Q/02x1r73IMZLytGqU/jquiBMHhUI=,tag:Qq5Wl/FrRjbje55wAxXk7A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:2KaP0KVH4HHnVYYa2JKY3RE=,iv:CSceEaOHy1d3fjpqbLyETDGc+rb3gSbjIi6KjjXPrjs=,tag:yMRx/Z4Xj6U7VNt6MYpgPg==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:yYMS243tSxDq,iv:sr//zr4cFEkN7z417C4CG4rPtDdZXIstEgy4KqzFfn4=,tag:W+thq9bzhrUdK9QTQsoaCQ==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:IhZh6sIs2j+SyZn6HwCk,iv:HOT8+ifdfkX6YOa7KqyndJKMf/QEcX080Mtk+KDGRQg=,tag:ePIqd3DIkHuP6OcMq1BooA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:Gf/LzYg=,iv:wT9yp2z7iUsV9foBJqDDgifdqbCwcmMbiA9mnz8iIts=,tag:ERqh7uNiqfhH4sKA5xn7Yw==,type:int]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:kEaKewY=,iv:aQjQLhU4KDE6ASKXOcuIc/lrjpGHserDFSS/hHIosXE=,tag:WXxWNgpOvBXD6CjrXoPoow==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbXcxV3QzbFpXU2pvbFFY
            VjVsUVFQdWVobUZXdXFGcjdhMFRNRktyZXlRCkZtOExsOXM3V0FuYTJBQmNoTlR2
            V2J6YlA5b3FZRXZ0ZmhoalQrZmZHQncKLS0tIDZjYlNCVHZCcWJMaVhVaVpHeDla
            d0srYm83akdneFljNDhZVDVsRGYyYzQK1KRCFLhqE2qM3xx4gvGiSEsPSxRqxpee
            vDiKfWXQWRjI1N8UUX8q47A6qSDhyn1yzwMdwbRrJ4O3wTG0bblIjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T04:58:24Z"
    mac: ENC[AES256_GCM,data:5JyAiB3JdXjpEH3lDeelIO+HwxdpMFK7B5ZvGqDXlS2fFwgBAvz2iXR1o6ajXeLOGuZCOUY3UDpvARiGxcpsY8nqQ35VTdW7+ffs1BZaz6f23z2FD7XayZziLZdAft7pbqGte0rrI200TPGY5IGJXutSuPOktte6JqUDtcj4a8o=,iv:0l5e0G0h2/Z3zv1bAdDFtNd44JOKN0rXwWuxuT08AuU=,tag:qGxY+mXfbpl7A79+AROgPQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
