apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:o9TIrg==,iv:Daksh/9DDXNOewibPHu1XRWtFfLM245h63KpPBbeLSE=,tag:Vmp8v48FF9I+YbmQQKws5A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:99EbHJeDdAdyjADAwur8QYHzEjaJh4YC6W/8gZwMVo2+rHzZhovDUiIWVei1,iv:DKFb6yWVxeiyNccqZZiWxIfcxV4cbuCNb8hykHrcHVc=,tag:pjRjVO7pBsq6Y+XaVtkiyw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:t2K5G/6pNcEvnqPgsXYhqB0=,iv:wmkR6e52mSpD5HUIPEV43fSDYrGao+6bLDihksNPXBA=,tag:UdxjHLqgm2C/ybCpB+CEVQ==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:TpQZMrto0tWGV21TN6Hn,iv:0aK+T7lllMvfW9vb6Xzn5KgjuAJyPL4p80gttZuvDew=,tag:uzaf+1vGXC6oWdKzQkgcxA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:qThZzw0=,iv:9INwVc0F89zXo+SI1SMk8/xTP4CTUkVjMW6VJEpJh94=,tag:AyGFf2VJvTEFWo1DuTzdpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcDFnYnBGVmVBbU9rVHRi
            cEtvbXVHYW02RW4xaHpjU2FqdGo0WnV5ZEhrCmorVnk4SlpWZjEvd09HcnlvcHMw
            V0RVa1RNVU1tUnFvQllCSEF2ZHJQRkUKLS0tIFlSV1lHWkZFbXVuNUJDa1hURytW
            U2g0azh0VW1vSVZvUnR6Y2ZQb2JvcmcKWx6kdPBztiWM7Zuf7aOVCpzQq0lRPaT6
            lTmLWNTWAK6TFwHAcjcZpDrmy8Zj5kbUvACOFW2jL8AJ+2oP8dRz1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T07:13:34Z"
    mac: ENC[AES256_GCM,data:j/5YSz3MwN2l1K3GAdvyag6QrDe6oNovSrT4UgmysBPNv1KCSbjyx5yEYBrfQ0YkdO5B6G7SoW3FQAW9j+IAWP6mStB5obD49YZoLn/kiI7pkrPgqpgY4e8tBp0dVZwGzvynDEfZrYCuNHldtuEmKCuEQxVKPDzMqBgoicka+aA=,iv:xt2U3xYJdKpfIwT8EYO+6gBW/vT0RdSwfH5NXxP2wYM=,tag:Y8Q61uCAhd1fOQEcBxaUvw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
