apiVersion: v1
kind: Secret
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:/hx0Og==,iv:FUbKMk34kWefow6wCtwlvaOTLI3ErRKWWT2vElTSs6A=,tag:cM8o2kTCdoygSizuZlb9mQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:j4K5afJg4roYZqj1aNkod1uJ8SAzB3AxZ0rQfM1AcOBIeQkfLavX8CBLHCQ=,iv:a0gdNuLbKyUxX3js9Zp4PnuMOmQ3o4k/wvCtPB4g0IU=,tag:EHH1xsYtSAFicQAfwme9JQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:vtydMAWHUOB5uzids3iND34=,iv:Pm70n1H7sa/OajGPzan8V7iy5L4F0q0Rr7i4fsMnDqU=,tag:1RkJDse0v2tzAgbo9jvOsw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:AnJlur9K1KJY,iv:zuuCi4xG7xiDMTQBMR5EIXvB2iGS8XIrufG0bYqIPIY=,tag:y2Zi7ZcISqdZrp1Bc4RzsA==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:p+u8RUBVrK+zYtxhz3JU,iv:61MxSiLsBxpPS2FgmKYHhKwcoH2mfBDWSw26kSUb3u4=,tag:QmgtJOWlf7ecP+/uanOgeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0JwNnU0bnY1VFloY0JC
            bDJoTjBaQTRKTS9NMGhtMDBWK2JnWUpQN2xRClpRTnMvdjB2Yk4wVTlyMjNjUVh3
            T08yY2k3U0lmayttVDFpdkVJVXp3TGcKLS0tIFFEUmVpdHp0YkpPUGV0MEozV0Fv
            dHloZ0FGUVNJTUs5cE41UjI4RjZGM1EKnx/Qvyry+e+PM/jaTMEltPM905BNyOUm
            3b2rqgtHl3dMeeC0p4p7mpvHmUqy+l7ppPmDHPd6I8zd3D+4Wq/Pmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T03:27:18Z"
    mac: ENC[AES256_GCM,data:cj97j+6B6L9KHvJdJ5fLu7Ngt0VHLWsuPoR1JQJfOf1i+440M5OeSB6ZOHP55adN2abCNbp9tfQQ2lozB8g5S9N0il6KRH17S2sOTR9iZY9/wZp0iUS48eE3NWaD/hdT0Uh9LQKdZzSTifIg5y7hl73NNLOWKojbz7deUELmhTg=,iv:oFbkVw3kvHaVJJTuNjbkpwmkTI5fnhp852NXkU7CxKM=,tag:bty7ra1eSNohRpbM09BvUw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
