---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.2.2
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-staging
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: authentik-tls
            hosts:
              - *host
    authentik:
      error_reporting:
        enabled: false
      log_level: "debug"

    postgresql:
      enabled: true
    redis:
      enabled: true
    prometheus:
      serviceMonitor:
        create: false
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
