apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:CkUHnw7SnVz52vcyweGWg8puWyM0zFmY+0viFeXbyjC82U270yg1pwkddWMAtH36WVa4C1KiI5oKuLbKxSEuN8M8VBSgK5TfehpUIV9xjmYD9xe9+a2HqAh59kuuMuIusLk51/vHgr3k8tsc5u8jeEH5DxcJrTBNEHm/gwPIxxjMXPd4UTMYZqPo78Mus+cBHXzUTi802lrUE3ZFq+UCi6f9nNwkTUqLJBFcAUeKfgNlOBrU/uYXb6R1M9jGt6aFxMHQ1tJAju0y2FsvjWqKIcEtvfXc87Oi43rKliU9QJKQ5vZSxgZUpkKek2Zg,iv:5jf0YxvJ+lOKbkSOhQ4OSOWTvsrTrXiCq89wvO/MYJs=,tag:v43ZxntNkZye0j8kPJ8W8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeVErYlgyWGxtdExNWUZE
            VzVTODl5M2dHdkltaG1maVNPTDR6cEV5Q3hjCnd0NTI5dXlmWHpqb0tIeUJPcTIw
            cHRYRzlyQzhnYzdiYWx0Vk85R2huTzQKLS0tIDQweXpuR09mejB6MVRhWlJnd1By
            bWpwLy8xb0FLZUZUekhDbVhPejhheDgK0Wy/LWVkMwnlJK2AS5tOYqUIPD8Y783k
            5IvOb5jTkiXdM0xLONZPOb1Z0o+0DKKCmJb1H9l1+yG+bXmMM1cjiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T08:16:43Z"
    mac: ENC[AES256_GCM,data:+ny3biCJLewB0nm89xvZ9H+IkZLnmNIZuH43we/QnUTnHdWa4MY4z8paZ+lmNeOMSr7ITW89BS6iZn0z+zh3fteaqe1QzPKP3TRb4K28zX4xf/+KFtFRWS6YpA+JkSQTd36Dwe2IV9bs4mzKuo/3IXvnSpQWVT4i16BLnuY4ed8=,iv:evu+Su8hORaMBpHlYU/+7U/Tdlz/6+NLUpqgqET2jBA=,tag:fvA+KDUTlRJhplnWRx7zcQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
