apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Xdg+mFpaz6pA1/txYRlJcxwnxaXK9jTAg5AsuOaDzRlqmiN+Xg==,iv:UNOoOUJ06jN4/+mdKv6dPOOsEW6/1S+L0MqE1Pahz+g=,tag:NUiKsGEc5ukZTpISlu2bYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7unxeay3lrlcel6dddh95uq565mf2yh43qsr3vnraps3rwx8elsl43pyg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OG9SMU1Wd0FUc3lWRFpJ
            V25TSksvSjIvZmFrWEFuWFZ6b0w2d2RGMGxZCklBWWFvUU9MTTBxT2dlZUZiN3hN
            WlE1ZXNrUjhVZlRIYm1GOGEwMG1yRmMKLS0tIGtMdGRmWER0QWtCMnMrdmhGQmxq
            OHEyS1dWcHdZSWo2OWhlVE9aMXozU0kKnrLdzZG6vDe4F4Ymu7kyNCEX+YeDzT03
            YOl+RtG6n0yeH0RSxuIR6dUHPfywWFRyzXEh0Gc8Glnv/GTOi5xkRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T13:02:56Z"
    mac: ENC[AES256_GCM,data:BTFJQfeypbdfxDUwCg8UBcGOqQgshz+OaPnTr6/kkegvUVrNjG4C/2GIndM8u2Rx3I3fpHimJ21CNJgoDx9b+I7w8hQiAOoJQGfyAtx5dYvS9BuVcC9v97WzKnFmmP3I3rVY2sP8d2lWsK6m9xvIzAnZqR4+v56JVsnvu/RKjR0=,iv:j04MVRYmx3tkjyQVuLUVPvBDPqWpmAijlpb71YONHYQ=,tag:kdUh5ysh53m5dYj3TTdv2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
