---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-appName101
  namespace: flux-system
spec:
  path: ./kubernetes/apps/appNamespace101/appName101/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: appName101
      namespace: appNamespace101
  interval: 3m
  retryInterval: 1m
  timeout: 3m
