---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-metallb
  namespace: longhorn-system
  annotations:
spec:
  ports:
    - port: 80
      targetPort: 80
      selector:
        app: longhorn-ui
        type: LoadBalancer
