---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ingress
  namespace: testing-longhorn
spec:
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: |
      10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    hajimari.io/enable: "false"
  hosts:
    - host: &host "longhorn.${SECRET_DOMAIN}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - *host
